name: Unity CI

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cache the Unity Library folder (speeds up builds)
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      # 3. Run Unity tests using a GitHub Action
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.0.43f1   # <-- change to your Unity version
          testMode: all              # options: editmode, playmode, all

      # 4. Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: artifacts
